### ISSUE TITLE
Spring project error

### ISSUE THREAD

**Issue by Little-Cat** [gleidsonmt/GNDecorator#5]
Hi. I try to use your librari for my project. I use spring on 15.0.1 jdk. But i cant compile Spring configuration because "Factory method 'gNDecorator' threw exception; nested exception is java.lang.NoClassDefFoundError: com/sun/javafx/css/converters/PaintConverter"
My method 
```
   @Bean
    public GNDecorator gNDecorator() {
        return new GNDecorator();
    }
```
Ho I can releas this error?

**Comment by gleidsonmt** [comment]
Get the new version in code page.
